In [3]:
import pandas as pd

In [4]:
cols=['sepal length in cm','sepal width in cm','petal length in cm','petal width in cm','species']

In [5]:
df= pd.read_csv('iris.csv',sep=",",names=cols)

In [7]:
df.head()

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa

In [6]:
df['species'].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [10]:
setosa = df[df["species"]=="Iris-setosa"]
versicolor = df[df["species"]=="Iris-versicolor"]
virginica = df[df["species"]=="Iris-virginica"]

In [11]:
setosa.head()
versicolor.head()
virginica.head()

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,species
100,6.3,3.3,6.0,2.5,Iris-virginica
101,5.8,2.7,5.1,1.9,Iris-virginica
102,7.1,3.0,5.9,2.1,Iris-virginica
103,6.3,2.9,5.6,1.8,Iris-virginica
104,6.5,3.0,5.8,2.2,Iris-virginica

In [12]:
versicolor.head()

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,species
50,7.0,3.2,4.7,1.4,Iris-versicolor
51,6.4,3.2,4.5,1.5,Iris-versicolor
52,6.9,3.1,4.9,1.5,Iris-versicolor
53,5.5,2.3,4.0,1.3,Iris-versicolor
54,6.5,2.8,4.6,1.5,Iris-versicolor

In [14]:
merged_data= pd.concat([setosa,versicolor])

In [16]:
merged_data.tail()

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,species
95,5.7,3.0,4.2,1.2,Iris-versicolor
96,5.7,2.9,4.2,1.3,Iris-versicolor
97,6.2,2.9,4.3,1.3,Iris-versicolor
98,5.1,2.5,3.0,1.1,Iris-versicolor
99,5.7,2.8,4.1,1.3,Iris-versicolor

In [19]:
sorted_data= df.sort_values(by="petal length in cm",ascending=False)

sorted_data.head()

In [20]:
transpose_data=df.transpose()

In [21]:
transpose_data.head()

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
sepal length in cm,5.1,4.9,4.7,4.6,5.0,5.4,4.6,5.0,4.4,4.9,...,6.7,6.9,5.8,6.8,6.7,6.7,6.3,6.5,6.2,5.9
sepal width in cm,3.5,3.0,3.2,3.1,3.6,3.9,3.4,3.4,2.9,3.1,...,3.1,3.1,2.7,3.2,3.3,3.0,2.5,3.0,3.4,3.0
petal length in cm,1.4,1.4,1.3,1.5,1.4,1.7,1.4,1.5,1.4,1.5,...,5.6,5.1,5.1,5.9,5.7,5.2,5.0,5.2,5.4,5.1
petal width in cm,0.2,0.2,0.2,0.2,0.2,0.4,0.3,0.2,0.2,0.1,...,2.4,2.3,1.9,2.3,2.5,2.3,1.9,2.0,2.3,1.8
species,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,Iris-setosa,...,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica,Iris-virginica

In [24]:
melted_data=pd.melt(df, id_vars=['species'],value_vars=['sepal length in cm', 'sepal width in cm', 'petal length in cm','petal width in cm'],
                      var_name='metric',
                      value_name='Value')

In [25]:
melted_data.head()

       species              metric  Value
0  Iris-setosa  sepal length in cm    5.1
1  Iris-setosa  sepal length in cm    4.9
2  Iris-setosa  sepal length in cm    4.7
3  Iris-setosa  sepal length in cm    4.6
4  Iris-setosa  sepal length in cm    5.0

In [28]:
pivot_data = melted_data.pivot_table(index='species',columns='metric',values='Value', aggfunc='mean')

pivot_data

metric,petal length in cm,petal width in cm,sepal length in cm,sepal width in cm
species,,,,
Iris-setosa,1.464,0.244,5.006,3.418
Iris-versicolor,4.260,1.326,5.936,2.770
Iris-virginica,5.552,2.026,6.588,2.974